import { ArrowUpRight } from 'lucide-react';
import Link from 'next/link';
import { Reveal } from '@/components/experience';

const founders=[
  {name:'NAYANTHARA',role:'CO-FOUNDER',image:'https://d1oifqlqvwd9ay.cloudfront.net/Images/Background/nayanthara.webp',copy:'Co-founder of Femi9, Nayanthara is described by Femi9 as an advocate for women whose search for comfort and confidence helped spark the brand.'},
  {name:'VIGNESH SHIVAN',role:'CO-FOUNDER',image:'https://d1oifqlqvwd9ay.cloudfront.net/Images/Background/vignesh.webp',copy:'Femi9 describes Vignesh Shivan as a creative force supporting the mission and the wider social purpose behind the brand.'},
  {name:'DR. GOMATHI',role:'FOUNDER',image:'https://d1oifqlqvwd9ay.cloudfront.net/Images/Background/gomathi.webp',copy:'Femi9 identifies Dr. Gomathi as the founder behind the development of its pads, combining medical insight with everyday women’s needs.'},
];

export default function About(){return <>
<section className="page-hero about-hero"><span className="micro">FEMI9 / ABOUT</span><div className="page-hero-grid"><div><h1 className="display">PERIOD CARE,<br/><i>REIMAGINED.</i></h1><p className="hero-copy">Comfort, care and confidence — presented through the people and products behind Femi9.</p></div><div className="hero-image-frame"><img src="https://d1oifqlqvwd9ay.cloudfront.net/Images/Background/nayan_gomathi.webp" alt="Femi9 founders and co-founder"/></div></div></section>
<section className="section"><div className="grid-2"><Reveal><div className="split-image about-story-image" style={{backgroundImage:'url(https://raw.githubusercontent.com/Aaron-Samuel05/femi9/main/public/assets/img/hero-studio-product.jpg)'}}/></Reveal><div><span className="micro">THE STORY</span><h2 className="display-sm">MORE THAN A<br/><i>PRODUCT.</i></h2><p className="lead">Femi9's published story focuses on period care built around comfort, confidence and consideration for the environment.</p><p className="lead">The brand also describes a wider mission of supporting women entrepreneurs with training, resources and a platform for their skills.</p></div></div></section>
<section className="founder-section"><div className="founder-heading"><span className="micro">THE PEOPLE BEHIND FEMI9</span><h2 className="display">MEET THE<br/><i>FOUNDERS.</i></h2><p className="lead">Official Femi9 founder photography, shown at full resolution with a clean editorial treatment.</p></div><div className="founder-grid">{founders.map((f,i)=><article className="founder-card" key={f.name}><div className="founder-image"><img src={f.image} alt={f.name}/><span>{String(i+1).padStart(2,'0')}</span></div><div className="founder-meta"><span>{f.role}</span><h3>{f.name}</h3><p>{f.copy}</p></div></article>)}</div></section>
<section className="section dark"><div className="grid-2"><div><span className="micro">THE FEMI9 APPROACH</span><h2 className="display">CARE THAT<br/><i>STARTS</i><br/>WITH CLARITY.</h2></div><div className="editorial-list"><div className="editorial-row"><strong>01</strong><h3>COMFORT</h3><p>Product formats organized around everyday use, flow and fit.</p></div><div className="editorial-row"><strong>02</strong><h3>DESIGN</h3><p>Real product photography and clear size choices before purchase.</p></div><div className="editorial-row"><strong>03</strong><h3>COMMUNITY</h3><p>A period-care experience connected to a wider women-led mission.</p></div></div></div></section>
<section className="section"><Link className="dark-button" href="/shop">EXPLORE THE PRODUCTS <ArrowUpRight/></Link></section>
</>}
