'use client';

import { useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowUpRight, Check, Menu, Minus, Plus, ShoppingBag, X } from 'lucide-react';
import { create } from 'zustand';

const products = [
  {id:'330-double',name:'FEMI9 330MM PADS — DOUBLE WINGS',flow:'HEAVY',usage:'NIGHT + DAY',description:'Extra-length with double wings for overnight security.',price:225,pack:'9 pads',length:'330MM',category:'PADS',badge:'BESTSELLER',accent:'blush'},
  {id:'290-large',name:'FEMI9 290MM PADS — LARGE',flow:'REGULAR',usage:'EVERYDAY',description:'The everyday large. Nine pads for a full, comfy cycle.',price:198,pack:'9 pads',length:'290MM',category:'PADS',badge:'',accent:'cream'},
  {id:'330-centre',name:'FEMI9 330MM PADS — CENTRE WINGS',flow:'HEAVY',usage:'NIGHT',description:'Extra-length with centre wings and a wider back.',price:225,pack:'9 pads',length:'330MM',category:'PADS',badge:'',accent:'sand'},
  {id:'290-starter',name:'FEMI9 290MM PADS — STARTER',flow:'TRY IT',usage:'EVERYDAY',description:'A three-pad starter to feel the Femi9 difference.',price:72,pack:'3 pads',length:'290MM',category:'PADS',badge:'TRIAL PACK',accent:'rose'},
  {id:'180-mini',name:'FEMI9 180MM MINI PADS',flow:'LIGHT FLOW',usage:'DAILY FRESHNESS',description:'Ultra-thin, breathable everyday protection for light flow, daily discharge, spotting, and minor urinary leakage.',price:99,pack:'30 pads',length:'180MM',category:'PADS',badge:'',accent:'mist'},
  {id:'period-panties',name:'FEMI9 PERIOD PANTIES',flow:'LEAK-PROOF',usage:'MEDIUM TO HEAVY',description:'Soft, breathable and reusable. A full night of protection you can wash and wear again.',price:649,pack:'Reusable',length:'—',category:'UNDERWEAR',badge:'NEW',accent:'mauve'}
] as const;

type CartItem = { productId: string; qty: number };
type CartState = { cart: CartItem[]; add: (id:string)=>void; dec:(id:string)=>void; remove:(id:string)=>void; clear:()=>void };
const useCart = create<CartState>((set)=>({cart:[],add:(id)=>set(s=>({cart:s.cart.some(i=>i.productId===id)?s.cart.map(i=>i.productId===id?{...i,qty:i.qty+1}:i):[...s.cart,{productId:id,qty:1}]})),dec:(id)=>set(s=>({cart:s.cart.flatMap(i=>i.productId===id?(i.qty>1?[{...i,qty:i.qty-1}]:[]):[i])})),remove:(id)=>set(s=>({cart:s.cart.filter(i=>i.productId!==id)})),clear:()=>set({cart:[]})}));

function ProductCard({p,onAdd}:{p:typeof products[number];onAdd:(id:string)=>void}){
  return <motion.article layout className="product-card" whileHover={{y:-5}} transition={{duration:.25}}>
    <div className={`product-art ${p.accent}`}><div className="pad-shape"><span>F9</span></div><div className="art-index">{p.length}</div>{p.badge&&<div className="badge">{p.badge}</div>}</div>
    <div className="product-copy"><div><div className="micro">{p.flow} · {p.usage}</div><h3>{p.name}</h3><p>{p.description}</p></div><div className="product-bottom"><strong>₹{p.price}</strong><span>{p.pack}</span><button onClick={()=>onAdd(p.id)} className="text-button">ADD TO BAG <ArrowUpRight size={15}/></button></div></div>
  </motion.article>
}

export default function Home(){
 const [menu,setMenu]=useState(false); const [finder,setFinder]=useState(false); const [flow,setFlow]=useState(''); const [time,setTime]=useState(''); const [pref,setPref]=useState(''); const [bagOpen,setBagOpen]=useState(false); const cart=useCart();
 const count=cart.cart.reduce((n,i)=>n+i.qty,0); const subtotal=cart.cart.reduce((n,i)=>n+(products.find(p=>p.id===i.productId)?.price||0)*i.qty,0);
 const match=useMemo(()=>products.find(p=>pref==='REUSABLE'?p.id==='period-panties':pref==='ULTRA-THIN'?p.id==='180-mini':flow==='HEAVY'&&time==='NIGHT'?p.id==='330-double':flow==='HEAVY'?p.id==='330-centre':flow==='LIGHT'?p.id==='180-mini':p.id==='290-large')||products[0],[flow,time,pref]);
 const add=(id:string)=>{cart.add(id);setBagOpen(true)};
 return <main>
  <header className="nav"><a className="logo" href="#top">FEMI9</a><nav className="desktop-nav"><a href="#shop">SHOP</a><a href="#why">WHY FEMI9</a><a href="#story">OUR STORY</a><a href="#finder">FIND YOUR FEMI9</a></nav><div className="nav-actions"><button onClick={()=>setBagOpen(true)} aria-label="Open bag"><ShoppingBag size={17}/><span>{count}</span></button><button onClick={()=>setMenu(true)} className="menu-trigger">MENU</button></div></header>
  <section id="top" className="hero"><div className="hero-bg"></div><div className="hero-grid"><div className="hero-kicker">PREMIUM PERIOD CARE / FEMI9</div><h1>EVERY FEMI9 PAD,<br/><em>IN ONE PLACE.</em></h1><p>Light, regular or heavy — choose the protection that matches your flow.</p><div className="hero-actions"><a className="primary" href="#shop">SHOP FEMI9 <ArrowUpRight size={17}/></a><button className="secondary" onClick={()=>setFinder(true)}>FIND YOUR FEMI9 <ArrowUpRight size={17}/></button></div></div><div className="hero-product"><div className="hero-product-card"><div className="pack-glow"></div><div className="hero-pack">FEMI<span>9</span><small>PERIOD CARE</small></div></div></div><div className="scroll-cue">SCROLL TO EXPLORE <span></span></div></section>
  <section className="statement"><span className="section-number">01</span><h2>PERIOD CARE<br/><em>SHOULD FEEL</em><br/>LIKE CARE.</h2><p>Thoughtful protection, clean design and an experience made to feel effortless.</p></section>
  <section id="why" className="feature"><div className="feature-image abstract-image"><div className="giant-word">FEMI9</div></div><div className="feature-copy"><div className="micro">02 / WHY FEMI9</div><h2>DESIGNED<br/>FOR YOUR<br/><em>REAL LIFE.</em></h2><div className="feature-list"><div><b>LIGHT</b><span>Ultra-thin everyday protection.</span></div><div><b>REGULAR</b><span>Comfort for your everyday flow.</span></div><div><b>HEAVY</b><span>Extra-length options for night and day.</span></div><div><b>REUSABLE</b><span>Soft period panties made to wash and wear again.</span></div></div></div></section>
  <section id="shop" className="shop"><div className="shop-head"><div><div className="micro">03 / SHOP FEMI9</div><h2>FIND THE FIT<br/><em>FOR YOUR FLOW.</em></h2></div><div className="shop-note">{products.length} PRODUCTS<br/><span>Protection, without the visual clutter.</span></div></div><div className="product-grid">{products.map(p=><ProductCard key={p.id} p={p} onAdd={add}/>)}</div></section>
  <section id="story" className="story"><div className="story-sticky"><div className="micro">04 / OUR STORY</div><h2>PERIOD CARE,<br/><em>REIMAGINED.</em></h2><p>Femi9 brings together practical protection and an intentional everyday experience. Move through the story in four beats.</p><a href="#finder" className="text-link">DISCOVER THE FEMI9 APPROACH <ArrowUpRight size={16}/></a></div><div className="story-steps"><article><span>01</span><h3>THE IDEA</h3><p>A period-care experience that feels considered, not clinical.</p></article><article><span>02</span><h3>THE DESIGN</h3><p>Product choices shaped around flow, use and day-to-day comfort.</p></article><article><span>03</span><h3>THE COMFORT</h3><p>Protection presented with softness, clarity and breathing room.</p></article><article><span>04</span><h3>THE EVERYDAY</h3><p>From light days to overnight protection, there is a Femi9 for the moment.</p></article></div></section>
  <section id="finder" className="finder"><div className="micro">05 / PRODUCT FINDER</div><h2>FIND YOUR<br/><em>FEMI9.</em></h2><p>Answer three quick questions and see a product match.</p><div className="finder-options"><button onClick={()=>setFlow('LIGHT')} className={flow==='LIGHT'?'selected':''}>LIGHT</button><button onClick={()=>setFlow('REGULAR')} className={flow==='REGULAR'?'selected':''}>REGULAR</button><button onClick={()=>setFlow('HEAVY')} className={flow==='HEAVY'?'selected':''}>HEAVY</button></div><div className="finder-options"><button onClick={()=>setTime('DAY')} className={time==='DAY'?'selected':''}>DAY</button><button onClick={()=>setTime('NIGHT')} className={time==='NIGHT'?'selected':''}>NIGHT</button><button onClick={()=>setTime('EVERYDAY')} className={time==='EVERYDAY'?'selected':''}>EVERYDAY</button></div><div className="finder-options"><button onClick={()=>setPref('ULTRA-THIN')} className={pref==='ULTRA-THIN'?'selected':''}>ULTRA-THIN</button><button onClick={()=>setPref('EXTRA-LENGTH')} className={pref==='EXTRA-LENGTH'?'selected':''}>EXTRA-LENGTH</button><button onClick={()=>setPref('REUSABLE')} className={pref==='REUSABLE'?'selected':''}>REUSABLE</button></div><AnimatePresence mode="wait"><motion.div key={match.id+flow+time+pref} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="match"><div className={`product-art ${match.accent}`}><div className="pad-shape"><span>F9</span></div></div><div><div className="micro">YOUR FEMI9 MATCH</div><h3>{match.name}</h3><p>{match.description}</p><strong>₹{match.price}</strong><button onClick={()=>add(match.id)} className="primary">ADD TO BAG <ArrowUpRight size={17}/></button></div></motion.div></AnimatePresence></section>
  <section className="newsletter"><div><div className="micro">06 / STAY CLOSE</div><h2>CARE IN<br/><em>YOUR INBOX.</em></h2></div><div className="newsletter-form"><input placeholder="YOUR EMAIL ADDRESS"/><button>SUBSCRIBE <ArrowUpRight size={17}/></button><small>Product news, stories and useful period-care updates.</small></div></section>
  <footer><div className="footer-top"><div className="footer-brand"><div className="footer-logo">FEMI9</div><p>Premium period care designed around real life.</p></div><div className="footer-links"><div><span>EXPLORE</span><a href="#shop">Shop</a><a href="#why">Why Femi9</a><a href="#story">Our Story</a><a href="#finder">Find Your Femi9</a></div><div><span>CONNECT</span><a href="mailto:support@femi9.in">support@femi9.in</a><a href="tel:+919042916499">+91 90429 16499</a><a href="https://instagram.com/femi9official">Instagram / @femi9official</a></div></div></div><div className="footer-bottom"><span>© Femi9 2026. All rights reserved.</span><span>222/1, Pavizham Nagar, Thindal, Erode, Tamil Nadu 638012</span><span>Privacy · Terms</span></div></footer>

  <AnimatePresence>{menu&&<motion.div className="menu-panel" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{duration:.45,ease:[.76,0,.24,1]}}><button onClick={()=>setMenu(false)} className="close"><X/></button><div className="menu-inner"><div className="menu-kicker">FEMI9 / EXPLORE</div>{['SHOP','WHY FEMI9','OUR STORY','FIND YOUR FEMI9','PERIODS WALL','AFFILIATE','OPPORTUNITIES','SIGN IN'].map((x,i)=><motion.a key={x} href={x==='SHOP'?'#shop':x==='WHY FEMI9'?'#why':x==='OUR STORY'?'#story':'#finder'} onClick={()=>setMenu(false)} initial={{opacity:0,x:30}} animate={{opacity:1,x:0}} transition={{delay:.08*i}}>{x}<ArrowUpRight size={19}/></motion.a>)}</div></motion.div>}</AnimatePresence>
  <AnimatePresence>{bagOpen&&<motion.aside className="bag" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{duration:.4,ease:[.76,0,.24,1]}}><div className="bag-head"><h2>YOUR BAG</h2><button onClick={()=>setBagOpen(false)}><X/></button></div>{cart.cart.length===0?<div className="empty"><p>YOUR BAG IS EMPTY.</p><span>Find the protection that feels right for you.</span><a href="#shop" onClick={()=>setBagOpen(false)} className="primary">SHOP FEMI9 <ArrowUpRight size={17}/></a></div>:<><div className="bag-items">{cart.cart.map(i=>{const p=products.find(p=>p.id===i.productId)!;return <div className="bag-item" key={i.productId}><div className={`mini-art ${p.accent}`}><span>F9</span></div><div><h3>{p.name}</h3><small>{p.pack}</small><div className="qty"><button onClick={()=>cart.dec(p.id)}><Minus size={14}/></button><span>{i.qty}</span><button onClick={()=>cart.add(p.id)}><Plus size={14}/></button><button onClick={()=>cart.remove(p.id)} className="remove">REMOVE</button></div></div><strong>₹{p.price*i.qty}</strong></div>})}</div><div className="bag-summary"><div><span>SUBTOTAL</span><strong>₹{subtotal}</strong></div><small>Shipping and payment are handled at checkout.</small><button className="primary full">CHECKOUT <ArrowUpRight size={17}/></button><button onClick={()=>setBagOpen(false)} className="continue">CONTINUE SHOPPING</button></div></>}</motion.aside>}</AnimatePresence>
  {finder&&<div className="quick-overlay" onClick={()=>setFinder(false)}><div className="quick" onClick={e=>e.stopPropagation()}><button onClick={()=>setFinder(false)} className="close"><X/></button><div className="micro">FIND YOUR FEMI9</div><h2>YOUR FLOW.<br/><em>YOUR FIT.</em></h2><p>Use the full finder below to explore Femi9 by flow, time and preference.</p><a href="#finder" onClick={()=>setFinder(false)} className="primary">START FINDER <ArrowUpRight size={17}/></a></div></div>}
 </main>
}
