import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { CinematicHero, Marquee, Reveal } from '@/components/experience';
import { blogPosts } from '@/lib/data';

const PRODUCT_IMAGE='https://femi9.in/uploads/Product/1773300828_jFWVIMppz1.webp';
const HERO_IMAGE='https://femi9.in/uploads/Product/1773127765_EA2vx1qoIA.webp';

export default function Home(){return <>
<CinematicHero/>
<Marquee/>
<section className="section intro-editorial"><div className="grid-2"><Reveal><div><span className="micro">01 / THE FEMI9 APPROACH</span><h2 className="display">PERIOD CARE<br/><i>WITHOUT</i><br/>THE CLUTTER.</h2></div></Reveal><Reveal><div className="glass-panel editorial-intro"><p className="lead">A quieter way to shop period care. Explore the product in detail first, understand what matters, then choose the format that fits your cycle.</p><div className="editorial-stat"><strong>ONE PRODUCT</strong><span>REAL PRODUCT VIEW · NO GUESSWORK</span></div></div></Reveal></div></section>
<section className="section dark cinematic-panel editorial-image-section"><div className="grid-2"><div className="split-image parallax-photo" style={{backgroundImage:`url(${HERO_IMAGE})`}}/><Reveal><div><span className="micro">02 / DESIGNED AROUND YOU</span><h2 className="display">LESS<br/><i>NOISE.</i><br/>MORE CARE.</h2><div className="editorial-list"><div className="editorial-row"><strong>LIGHT</strong><h3>180 MM</h3><p>For light flow, spotting and everyday freshness.</p></div><div className="editorial-row"><strong>REGULAR</strong><h3>290 MM</h3><p>A balanced everyday coverage format.</p></div><div className="editorial-row"><strong>HEAVY</strong><h3>330 MM</h3><p>Extra length for heavier-flow and overnight moments.</p></div></div></div></Reveal></div></section>
<section className="section product-image-showcase"><div className="showcase-grid"><div><span className="micro">02.5 / SEE THE REAL PRODUCT</span><h2 className="display-sm">REAL PACK.<br/><i>REAL DETAIL.</i></h2><p className="lead">Every major shopping surface now uses official Femi9 product photography instead of empty image boxes or generated placeholders.</p><Link href="/shop" className="dark-button">VIEW THE RANGE <ArrowUpRight/></Link></div><div className="showcase-image"><img src={PRODUCT_IMAGE} alt="Femi9 330mm Extra-Large 9 Pads Double Wings"/></div></div></section>
<section className="section material-editorial"><div className="editorial-wide"><span className="micro">03 / THE DETAILS MATTER</span><h2 className="display">SEE THE<br/><i>LAYERS.</i></h2><p className="lead narrow">Comfort, coverage and fit should be understandable before you buy. The product view above is built from Femi9's real 360° asset sequence, with official product photography as a resilient fallback.</p></div><div className="layer-strip"><div className="layer-card"><span>01</span><strong>SOFT FEEL</strong><p>Cotton-soft contact layer designed for comfortable wear.</p></div><div className="layer-card"><span>02</span><strong>SECURE FIT</strong><p>Wing options and longer formats for different routines.</p></div><div className="layer-card"><span>03</span><strong>EVERYDAY PROTECTION</strong><p>Coverage choices organized around how your cycle actually moves.</p></div></div></section>
<section className="section fit-stage"><div className="fit-stage-head"><div><span className="micro">04 / FIND YOUR FORMAT</span><h2 className="display">YOUR FLOW.<br/><i>YOUR FIT.</i></h2></div><p className="lead">No price wall. No product maze. Start with what you need, then configure your exact pack on the next step.</p></div><div className="fit-rail"><div className="fit-card"><span>LIGHT DAYS</span><strong>180 MM</strong><p>Light flow · spotting · daily freshness</p></div><div className="fit-card featured"><span>EVERYDAY</span><strong>290 MM</strong><p>Regular flow · everyday coverage</p></div><div className="fit-card"><span>HEAVIER DAYS</span><strong>330 MM</strong><p>Heavy flow · night + day</p></div></div><div className="fit-cta"><Link href="/product/p330dw" className="dark-button">CHOOSE YOUR FORMAT <ArrowUpRight/></Link></div></section>
<section className="section gold-stage conversion-final"><div className="gold-orb orb-a"/><div className="gold-orb orb-b"/><div className="conversion-final-inner"><span className="micro">05 / TAKE YOUR TIME</span><h2 className="display">THE PRODUCT<br/><i>IS RIGHT THERE.</i></h2><p className="lead">Rotate it. Inspect it. Then configure the pack that makes sense for you.</p><Link href="/product/p330dw" className="light-button">CONTINUE TO PRODUCT <ArrowUpRight/></Link></div></section>
<section className="section dark story-stage"><div className="grid-2"><div><span className="micro">06 / OUR STORY</span><h2 className="display">CARE THAT<br/><i>STARTS</i><br/>WITH CLARITY.</h2></div><Reveal><div className="editorial-list"><div className="editorial-row"><strong>01</strong><h3>THE IDEA</h3><p>Period care that feels considered, not clinical.</p></div><div className="editorial-row"><strong>02</strong><h3>THE DESIGN</h3><p>Choices organized around flow, use and comfort.</p></div><div className="editorial-row"><strong>03</strong><h3>THE COMMUNITY</h3><p>A brand experience built around real everyday care.</p></div><Link className="light-button" href="/about">READ OUR STORY <ArrowUpRight/></Link></div></Reveal></div></section>
<section className="section"><span className="micro">07 / JOURNAL</span><h2 className="display">PERIOD HEALTH.<br/><i>REAL TALK.</i></h2><div className="blog-grid" style={{marginTop:60}}>{blogPosts.slice(0,4).map(p=><Link className="blog-card" href={`/blog/${p.slug}`} key={p.slug}><div><span>{p.category} · {p.date}</span><h2>{p.title}</h2></div><ArrowUpRight/></Link>)}</div></section>
<section className="section dark"><div className="grid-2"><div><span className="micro">08 / COMMUNITY</span><h2 className="display">PERIODS<br/><i>WALL.</i></h2><p className="lead" style={{color:'#bdb2ac'}}>A dedicated place for community stories and supplied customer content.</p></div><Link href="/periods-wall" className="light-button">ENTER THE WALL <ArrowUpRight/></Link></div></section>
<footer className="section dark" style={{paddingBottom:35}}><div className="grid-2"><div><div className="display-sm">FEMI9</div><p style={{color:'#9f958f',maxWidth:320}}>Care for your period, care for our earth.</p></div><div className="editorial-list"><div className="editorial-row"><strong>EXPLORE</strong><p><Link href="/shop">Shop</Link> · <Link href="/about">About</Link> · <Link href="/blog">Journal</Link> · <Link href="/contact">Contact</Link></p></div><div className="editorial-row"><strong>SUPPORT</strong><p>support@femi9.in<br/>+91 90429 16499<br/>222/1, Pavizham Nagar, Thindal, Erode, Tamil Nadu 638012</p></div></div></div></footer>
<style jsx global>{`
.product-image-showcase{background:#fffdf3}.showcase-grid{display:grid;grid-template-columns:.8fr 1.2fr;gap:7vw;align-items:center}.showcase-image{min-height:620px;border-radius:36px;overflow:hidden;background:#f1d276;display:grid;place-items:center;box-shadow:0 30px 90px rgba(72,52,8,.16)}.showcase-image img{width:100%;height:100%;max-height:680px;object-fit:cover}.blog-card{overflow:hidden}
@media(max-width:900px){.showcase-grid{grid-template-columns:1fr}.showcase-image{min-height:430px}.showcase-image img{height:430px}}
`}</style>
</>}
