import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { CinematicHero, Marquee, ProductCard, Reveal } from '@/components/experience';
import { PadTurntable } from '@/components/pad-turntable';
import { products, blogPosts } from '@/lib/data';

export default function Home(){return <>
<CinematicHero/><Marquee/>
<section className="section glass-section"><div className="grid-2"><Reveal><><span className="micro">01 / THE FEMI9 APPROACH</span><h2 className="display">PERIOD CARE<br/><i>SHOULD FEEL</i><br/>LIKE CARE.</h2></></Reveal><Reveal><div className="glass-panel"><p className="lead">Femi9 is built around comfort, confidence and practical protection — with products designed for different flows, lengths and everyday moments.</p><Link className="dark-button" href="/about">WHY FEMI9 <ArrowUpRight/></Link></div></Reveal></div></section>
<section className="section dark cinematic-panel"><div className="grid-2"><div className="split-image parallax-photo" style={{backgroundImage:'url(https://raw.githubusercontent.com/Aaron-Samuel05/femi9/main/public/assets/img/exact-user-hero.jpg)'}}/><Reveal><span className="micro">02 / PROTECTION</span><h2 className="display">DESIGNED FOR<br/><i>REAL LIFE.</i></h2><div className="editorial-list"><div className="editorial-row"><strong>LIGHT</strong><h3>180MM</h3><p>Everyday freshness for light flow, spotting and daily discharge.</p></div><div className="editorial-row"><strong>REGULAR</strong><h3>290MM</h3><p>Everyday coverage with a larger format.</p></div><div className="editorial-row"><strong>HEAVY</strong><h3>330MM</h3><p>Extra-length options for night and heavier flow.</p></div><div className="editorial-row"><strong>PACKS</strong><h3>3 / 6 / 9</h3><p>Choose the pack size that fits your routine and cycle.</p></div></div></Reveal></div></section>
<section className="section product-experience"><div className="grid-2"><div className="sticky-copy"><span className="micro">03 / THE PRODUCT EXPERIENCE</span><h2 className="display">SEE IT<br/><i>FROM EVERY</i><br/>ANGLE.</h2><p className="lead">This is not a fabricated 3D pad. The viewer uses the real Femi9 360° product frames already present in the original website assets.</p><div className="glass-panel mini-panel"><strong>42 FRAME TURNAROUND</strong><span>DRAG · SCROLL · INSPECT</span></div></div><Reveal><PadTurntable className="hero-turntable"/></Reveal></div></section>
<section className="section gold-stage"><div className="gold-orb orb-a"/><div className="gold-orb orb-b"/><div className="grid-2"><Reveal><span className="micro">04 / MATERIAL + COMFORT</span><h2 className="display">SOFT<br/><i>BY DESIGN.</i></h2></Reveal><Reveal><div className="glass-panel glass-dark"><p className="lead">Femi9's current site positions its pads around cotton-soft comfort, breathable layers and protection for different flow levels.</p><Link className="light-button" href="/shop">EXPLORE THE RANGE <ArrowUpRight/></Link></div></Reveal></div></section>
<section className="shop-intro"><div><span className="micro">05 / SHOP</span><h1>FIND YOUR<br/><i>FEMI9.</i></h1></div><p>Real Femi9 product photography, clear flow information and an editorial shopping experience built around the product rather than a generic grid.</p></section>
<section className="product-grid">{products.map(p=><ProductCard key={p.id} product={p}/>)}</section>
<section className="section dark story-stage"><div className="grid-2"><div><span className="micro">06 / OUR STORY</span><h2 className="display">FROM THE<br/><i>IDEA</i> TO<br/>EVERYDAY.</h2></div><Reveal><div className="editorial-list"><div className="editorial-row"><strong>01</strong><h3>THE IDEA</h3><p>Period care that feels considered, not clinical.</p></div><div className="editorial-row"><strong>02</strong><h3>THE DESIGN</h3><p>Product choices organized around flow, use and comfort.</p></div><div className="editorial-row"><strong>03</strong><h3>THE COMMUNITY</h3><p>A brand built around women, wellbeing and practical everyday care.</p></div><Link className="light-button" href="/about">READ OUR STORY <ArrowUpRight/></Link></div></Reveal></div></section>
<section className="section"><span className="micro">07 / JOURNAL</span><h2 className="display">PERIOD HEALTH.<br/><i>REAL TALK.</i></h2><div className="blog-grid" style={{marginTop:60}}>{blogPosts.slice(0,4).map(p=><Link className="blog-card" href={`/blog/${p.slug}`} key={p.slug}><div><span>{p.category} · {p.date}</span><h2>{p.title}</h2></div><ArrowUpRight/></Link>)}</div></section>
<section className="section dark"><div className="grid-2"><div><span className="micro">08 / COMMUNITY</span><h2 className="display">PERIODS<br/><i>WALL.</i></h2><p className="lead" style={{color:'#bdb2ac'}}>A dedicated place for community stories and supplied customer content — never fabricated testimonials.</p></div><Link href="/periods-wall" className="light-button">ENTER THE WALL <ArrowUpRight/></Link></div></section>
<section className="section"><div className="grid-2"><div><span className="micro">09 / STAY CLOSE</span><h2 className="display">CARE IN<br/><i>YOUR INBOX.</i></h2></div><div className="glass-panel"><p className="lead">Product updates, period-care education and new Femi9 stories.</p><input style={{width:'100%',border:0,borderBottom:'1px solid var(--line)',background:'transparent',padding:'18px 0',outline:0}} placeholder="YOUR EMAIL ADDRESS"/><button className="dark-button" style={{marginTop:18,border:0}}>SUBSCRIBE <ArrowUpRight/></button></div></div></section>
<footer className="section dark" style={{paddingBottom:35}}><div className="grid-2"><div><div className="display-sm">FEMI9</div><p style={{color:'#9f958f',maxWidth:320}}>Care for your period, care for our earth.</p></div><div className="editorial-list"><div className="editorial-row"><strong>EXPLORE</strong><p><Link href="/shop">Shop</Link> · <Link href="/about">About</Link> · <Link href="/blog">Journal</Link> · <Link href="/contact">Contact</Link></p></div><div className="editorial-row"><strong>SUPPORT</strong><p>support@femi9.in<br/>+91 90429 16499<br/>222/1, Pavizham Nagar, Thindal, Erode, Tamil Nadu 638012</p></div></div></div></footer>
</>}
