'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { AnimatePresence, motion, useScroll, useTransform } from 'framer-motion';
import { ArrowUpRight, Menu, Minus, Plus, ShoppingBag, X } from 'lucide-react';
import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import * as THREE from 'three';
import { products, type Product } from '@/lib/data';

export const useCart = create<{items:{id:string;qty:number}[];add:(id:string)=>void;dec:(id:string)=>void;remove:(id:string)=>void}>()(
  persist((set)=>({items:[],add:(id)=>set(s=>({items:s.items.some(i=>i.id===id)?s.items.map(i=>i.id===id?{...i,qty:i.qty+1}:i):[...s.items,{id,qty:1}]})),dec:(id)=>set(s=>({items:s.items.flatMap(i=>i.id===id?(i.qty>1?[{...i,qty:i.qty-1}]:[]):[i])})),remove:(id)=>set(s=>({items:s.items.filter(i=>i.id!==id)}))}),{name:'femi9-bag'}));

export function ThreePad(){
  const ref=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(!ref.current)return;const el=ref.current;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(34,el.clientWidth/el.clientHeight,.1,100);camera.position.set(0,0,6);const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.setSize(el.clientWidth,el.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;el.appendChild(renderer.domElement);const group=new THREE.Group();scene.add(group);const shape=new THREE.Shape();const w=1.45,h=3.3,r=.38;shape.moveTo(-w/2+r,-h/2);shape.lineTo(w/2-r,-h/2);shape.quadraticCurveTo(w/2,-h/2,w/2,-h/2+r);shape.lineTo(w/2,h/2-r);shape.quadraticCurveTo(w/2,h/2,w/2-r,h/2);shape.lineTo(-w/2+r,h/2);shape.quadraticCurveTo(-w/2,h/2,-w/2,h/2-r);shape.lineTo(-w/2,-h/2+r);shape.quadraticCurveTo(-w/2,-h/2,-w/2+r,-h/2);const geo=new THREE.ExtrudeGeometry(shape,{depth:.18,bevelEnabled:true,bevelSegments:4,bevelSize:.07,bevelThickness:.05});geo.center();const body=new THREE.Mesh(geo,new THREE.MeshPhysicalMaterial({color:0xf7f2ed,roughness:.42,metalness:.03,clearcoat:.45}));group.add(body);const wingGeo=new THREE.BoxGeometry(1.25,.82,.08);[-1,1].forEach(side=>{const wing=new THREE.Mesh(wingGeo,new THREE.MeshPhysicalMaterial({color:0xe8d5d0,roughness:.5}));wing.position.set(side*.92,-.05,.02);wing.rotation.z=side*.15;group.add(wing)});const strip=new THREE.Mesh(new THREE.BoxGeometry(.13,2.2,.045),new THREE.MeshStandardMaterial({color:0xb46b73,roughness:.6}));strip.position.z=.12;group.add(strip);const ring=new THREE.Mesh(new THREE.TorusGeometry(.62,.012,8,64),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.35}));ring.rotation.x=Math.PI/2;ring.position.z=.13;group.add(ring);scene.add(new THREE.HemisphereLight(0xfff4ef,0x3c2b27,2.2));const key=new THREE.DirectionalLight(0xffffff,3);key.position.set(3,4,5);scene.add(key);const fill=new THREE.PointLight(0xd98d94,2,8);fill.position.set(-3,1,2);scene.add(fill);let raf=0,mx=0,my=0;const onMove=(e:PointerEvent)=>{mx=(e.clientX/window.innerWidth-.5)*.8;my=(e.clientY/window.innerHeight-.5)*.5};window.addEventListener('pointermove',onMove);const animate=()=>{group.rotation.y+=(mx-group.rotation.y)*.035;group.rotation.x+=(-my-group.rotation.x)*.035;group.position.y=Math.sin(performance.now()*.0007)*.08;renderer.render(scene,camera);raf=requestAnimationFrame(animate)};animate();const resize=()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)};const ro=new ResizeObserver(resize);ro.observe(el);return()=>{cancelAnimationFrame(raf);ro.disconnect();window.removeEventListener('pointermove',onMove);renderer.dispose();geo.dispose();renderer.domElement.remove()}},[]);
  return <div ref={ref} className="three-pad" aria-label="Interactive 3D Femi9 pad"/>;
}

export function Header(){const [menu,setMenu]=useState(false);const [bag,setBag]=useState(false);const count=useCart(s=>s.items.reduce((a,i)=>a+i.qty,0));return <><header className="site-nav"><Link href="/" className="brand"><img src="https://raw.githubusercontent.com/Aaron-Samuel05/femi9/main/public/assets/img/logo.png" alt="Femi9"/></Link><nav><Link href="/shop">SHOP</Link><Link href="/about">WHY FEMI9</Link><Link href="/about">OUR STORY</Link><Link href="/blog">JOURNAL</Link><Link href="/affiliate">OPPORTUNITIES</Link></nav><div className="nav-tools"><button onClick={()=>setBag(true)} aria-label="Open shopping bag"><ShoppingBag size={17}/><sup>{count}</sup></button><button onClick={()=>setMenu(true)} aria-label="Open menu"><Menu size={19}/></button></div></header><AnimatePresence>{menu&&<motion.div className="menu-screen" initial={{clipPath:'inset(0 0 0 100%)'}} animate={{clipPath:'inset(0 0 0 0)'}} exit={{clipPath:'inset(0 0 0 100%)'}}><button className="menu-close" onClick={()=>setMenu(false)}><X/></button><div className="menu-links">{[['SHOP','/shop'],['WHY FEMI9','/about'],['OUR STORY','/about'],['JOURNAL','/blog'],['PERIODS WALL','/periods-wall'],['AFFILIATE','/affiliate'],['OPPORTUNITIES','/partner'],['FAQ','/faq'],['CONTACT','/contact']].map(([label,href],i)=><motion.div key={label} initial={{y:40,opacity:0}} animate={{y:0,opacity:1}} transition={{delay:i*.045}}><Link onClick={()=>setMenu(false)} href={href}>{label}<ArrowUpRight/></Link></motion.div>)}</div></motion.div>}</AnimatePresence><CartDrawer open={bag} onClose={()=>setBag(false)}/></>}

export function CartDrawer({open,onClose}:{open:boolean;onClose:()=>void}){const {items,add,dec,remove}=useCart();const total=items.reduce((sum,i)=>sum+(products.find(p=>p.id===i.id)?.price||0)*i.qty,0);return <AnimatePresence>{open&&<motion.aside className="cart-drawer" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{duration:.45,ease:[.76,0,.24,1]}}><div className="drawer-head"><span>SHOPPING BAG</span><button onClick={onClose}><X/></button></div>{items.length===0?<div className="drawer-empty"><div>NOTHING POURED YET.</div><p>Your bag is waiting for something that feels right.</p><Link href="/shop" onClick={onClose} className="dark-button">EXPLORE FEMI9 <ArrowUpRight/></Link></div>:<><div className="drawer-items">{items.map(i=>{const p=products.find(x=>x.id===i.id)!;return <div className="drawer-item" key={i.id}><img src={p.image} alt=""/><div><b>{p.name}</b><small>{p.pack} · ₹{p.price}</small><div className="qty"><button onClick={()=>dec(p.id)}><Minus size={12}/></button><span>{i.qty}</span><button onClick={()=>add(p.id)}><Plus size={12}/></button><button className="remove" onClick={()=>remove(p.id)}>REMOVE</button></div></div><strong>₹{p.price*i.qty}</strong></div>})}</div><div className="drawer-total"><span>SUBTOTAL</span><strong>₹{total}</strong></div><Link href="/checkout" onClick={onClose} className="dark-button wide">CHECKOUT <ArrowUpRight/></Link></>}</motion.aside>}</AnimatePresence>}

export function ProductCard({product}:{product:Product}){const add=useCart(s=>s.add);return <motion.article className="lux-card" initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.18}} transition={{duration:.7}}><Link href={`/product/${product.slug}`}><div className={`lux-art ${product.accent}`}><img src={product.image} alt={product.name}/>{product.badge&&<span className="art-badge">{product.badge}</span>}<span className="art-arrow"><ArrowUpRight/></span></div></Link><div className="card-meta"><span>{product.flow.toUpperCase()} · {product.usage.toUpperCase()}</span><small>{product.length}</small></div><Link href={`/product/${product.slug}`}><h3>{product.name}</h3></Link><p>{product.description}</p><div className="card-buy"><b>₹{product.price}</b><small>{product.pack}</small><button onClick={()=>add(product.id)}>ADD TO BAG <ArrowUpRight/></button></div></motion.article>}

export function Reveal({children,className=''}:{children:React.ReactNode;className?:string}){return <motion.div className={className} initial={{opacity:0,y:45}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.18}} transition={{duration:.8,ease:[.22,1,.36,1]}}>{children}</motion.div>}

export function CinematicHero(){const ref=useRef<HTMLElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start start','end start']});const y=useTransform(scrollYProgress,[0,1],[0,-180]);const scale=useTransform(scrollYProgress,[0,1],[1,1.12]);return <section ref={ref} className="cinema-hero"><div className="hero-media" style={{backgroundImage:'url(https://raw.githubusercontent.com/Aaron-Samuel05/femi9/main/public/assets/img/hero-full-studio.webp)'}}/><div className="hero-shade"/><motion.div className="hero-copy" style={{y}}><span className="eyebrow">FEMI9 / PERIOD CARE</span><h1>Care for your<br/><i>period.</i></h1><p>Designed around comfort, confidence and real everyday flow.</p><div className="hero-ctas"><Link href="/shop" className="light-button">SHOP FEMI9 <ArrowUpRight/></Link><Link href="/about" className="outline-button">DISCOVER THE STORY</Link></div></motion.div><motion.div className="hero-3d" style={{scale}}><ThreePad/></motion.div><div className="hero-scroll">SCROLL <span/></div></section>}

export function Marquee(){return <div className="marquee"><div>FEMI9 <span>COMFORT</span> FEMI9 <span>CONFIDENCE</span> FEMI9 <span>PROTECTION</span> FEMI9 <span>EVERYDAY</span> FEMI9 <span>COMFORT</span></div></div>}
